import 'package:boilerplate/models/answer/answer.dart';
import 'package:boilerplate/models/question/question.dart';
import 'package:boilerplate/models/question/question_list.dart';
import 'package:boilerplate/models/technical_name/technical_name.dart';
import 'package:boilerplate/models/translation/translation.dart';
import 'package:boilerplate/models/translation/translation_list.dart';
import 'package:boilerplate/models/step/step.dart' as StepModel;

class QuestionTest {
  QuestionList questions = QuestionList(questions: [
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            "Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "TEXT",
      axis_count: 1,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: ''),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: ''),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: ''),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: ''),
      ],
    ),
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            "Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "IMAGE",
      axis_count: 2,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
      ],
    ),
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            "Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "IMAGE",
      axis_count: 2,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
      ],
    ),
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            "Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "IMAGE",
      axis_count: 2,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
      ],
    ),
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            "Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "IMAGE",
      axis_count: 2,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "Title",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
      ],
    ),
    Question(
      id: 0,
      title: TechnicalName(
        id: 0,
        technical_name: "Question",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      sub_title: TechnicalName(
        id: 0,
        technical_name:
            " Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1Sub Title 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      type: "IMAGE",
      axis_count: 2,
      is_multiple_choice: false,
      info_url: TechnicalName(
        id: 0,
        technical_name: "Info URL 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      info_description: TechnicalName(
        id: 0,
        technical_name: "Info Description 1",
        translations: TranslationList(translations: []),
        creator_id: 1,
        created_at: '',
        updated_at: '',
      ),
      answer_required: 1,
      answers_selected_by_default: false,
      creator_id: 1,
      created_at: "2021-09-01 00:00:00",
      updated_at: '2021-09-01 00:00:00',
      step: StepModel.Step(
          id: 0,
          name: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          description: TechnicalName(
            id: 0,
            technical_name: "Info URL 1",
            translations: TranslationList(translations: []),
            creator_id: 1,
            created_at: '',
            updated_at: '',
          ),
          order: 1,
          image: '',
          tasks: []),
      answers: [
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
        Answer(
            id: 0,
            question_id: 1,
            title: TechnicalName(
              id: 0,
              technical_name: "",
              translations: TranslationList(translations: []),
              creator_id: 1,
              created_at: '',
              updated_at: '',
            ),
            order: 1,
            is_enabled: true,
            creator_id: '',
            created_at: '',
            updated_at: '',
            image:
                'https://play-lh.googleusercontent.com/5e7z5YCt7fplN4qndpYzpJjYmuzM2WSrfs35KxnEw-Ku1sClHRWHoIDSw3a3YS5WpGcI'),
      ],
    ),
  ]);
}
